# Generated by Django 2.2.3 on 2021-05-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=10)),
                ('precio', models.CharField(max_length=10)),
                ('pordata', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='Licores')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Categoria')),
            ],
        ),
    ]
