# Generated by Django 2.2.3 on 2021-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_cliente_consecutivo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(default=''),
        ),
    ]
