# Generated by Django 2.2.3 on 2021-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_producto',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_total',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
