# Generated by Django 2.2.3 on 2021-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_auto_20210507_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='domicilio',
            field=models.CharField(default=5000, max_length=7),
        ),
    ]
