# Generated by Django 2.2.3 on 2021-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_masvendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
